kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-efs-sc
  namespace: jenkins
provisioner: provisioner: efs.csi.aws.com
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  namespace: jenkins
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-efs-sc 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-098fd096f2fcc4111
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: jenkins-efs-sc
 
